# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  edgekv:
    type: boolean
    default: false
  production:
    type: boolean
    default: true

jobs:
  build:
    docker:
      - image: akamai/edgeworkers
    environment:
      EWVERSION: 0.60
      EWID: 4885
      BUNDLENAME: ew-bundle.tgz
      DESCRIPTION: "EW Deployment Automation with CircleCI - Support for EdgeKV"
    working_directory: /root/edgeworkers
    steps:
      - checkout
      - run:
          name: "Deugging"
          command: |
            pwd
            ls -lhart
            cd ~
            pwd
      - persist_to_workspace:
          root: ~/
          paths: edgeworkers
      - run: 
          name: "Build .edgerc file"
          command: echo -e "[default]\nclient_secret = $CLIENT_SECRET\nhost = $HOST\naccess_token = $ACCESS_TOKEN\nclient_token = $CLIENT_TOKEN" > .edgerc
      - when: 
          condition: << pipeline.parameters.edgekv >>
          steps: 
            - run: 
                name: "Add token to edgekv_tokens.js file"
                command: |
                  sed -i 's|EDGEKV_NAMESPACE|'$EDGEKV_NAMESPACE'|g' edgekv_tokens.js
                  sed -i 's|EDGEKV_TOKEN_NAME|'$EDGEKV_TOKEN_NAME'|g' edgekv_tokens.js
                  sed -i 's|EDGEKV_TOKEN_VALUE|'$EDGEKV_TOKEN_VALUE'|g' edgekv_tokens.js   
      - run:
          name: "Create and Upload Artifact"
          command: |
            sed -i 's|EWVERSION|'$EWVERSION'|g' bundle.json
            sed -i "s|DESCRIPTION|$DESCRIPTION|g" bundle.json
            tar -czvf ./$BUNDLENAME $( find -name "*.js" -or -name "*.json" | cut -c 3-)
            akamai ew upload --bundle ./$BUNDLENAME $EWID --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
      - store_artifacts:
          path: ew-bundle.tgz
  
  deploy:
    docker:
      - image: akamai/edgeworkers
    environment:
      EWVERSION: 0.60
      EWID: 4885
    working_directory: /root/edgeworkers
    steps:  
      - attach_workspace:
          at: /root
      - run: 
          name: "Activate EdgeWorkers to Staging"
          command: |
            pwd
            ls
            akamai ew activate $EWID STAGING $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
            akamai ew status $EWID --versionId $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY    
      - when: 
          condition: << pipeline.parameters.production >>
          steps: 
            - run: 
                name: "Activate EdgeWorkers to Production"
                command: akamai ew activate $EWID PRODUCTION $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
      - run:
          name: "Activation in Progress"
          command: while :; do OUTPUT=`akamai ew status $EWID --versionId $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY | awk '/PRESUBMIT|PENDING|IN_PROGRESS/ { print $4 }'`; if [ -z $OUTPUT ]; then echo Activation COMPLETE; break; else sleep 5; fi; done
      - run:
          name: "Enable Enhanced Debugging Token"
          command: |
            akamai ew --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY auth --expiry 60 --acl / --network staging $HOSTNAME || true 

workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - edgerc

      - deploy:
          requires:
            - build
          context:
            - edgerc
          post-steps:
            - run: 
                name: "Remove .edgerc"
                command: rm -r .edgerc