# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: akamai/edgeworkers
    environment:
      EWVERSION: 0.36
      EWID: 4885
      ACCOUNTKEY: 1-6JHGX
      BUNDLENAME: jaescalo-testing.tgz
      DESCRIPTION: "Adding IN_PROGRESS case"
    working_directory: /root/edgeworkers
    steps:
      - checkout
      - run: 
          name: "Build .edgerc file"
          command: echo -e "[default]\nclient_secret = $client_secret\nhost = $host\naccess_token = $access_token\nclient_token = $client_token" > .edgerc

      - run: echo "{"edgeworker-version":\"$EWVERSION\","description":\"$DESCRIPTION\"}" > bundle.json
      - run: tar -czvf ./$BUNDLENAME main.js bundle.json
      - run: akamai ew upload --bundle ./$BUNDLENAME $EWID --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
      - run: akamai ew activate $EWID STAGING $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
      - run: akamai ew status $EWID --versionId $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
      - run: while :; do OUTPUT=`akamai ew status $EWID --versionId $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY | awk '/PRESUBMIT|PENDING|IN_PROGRESS/ { print $4 }'`; echo Activation status is $OUTPUT; if [ -z $OUTPUT ]; then echo Activation COMPLETE; break; else sleep 5; fi; done

workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - edgerc
          pre-steps:
            - run:
                name: "Install jq"
                command: apk add --upgrade jq
          post-steps:
            - run: 
                name: "Remove .edgerc"
                command: rm -r .edgerc
      - node/test