# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - edgerc

jobs:
  build:
    docker:
      - image: akamai/edgeworkers

    environment:
      EWVERSION: 0.11
      EWID: 4885
      ACCOUNTKEY: 1-6JHGX

    steps:
      - run: pwd
      - run: echo "[default]" > .edgerc
      - run: echo client_secret = $client_secret >> .edgerc
      - run: echo host = $host >> .edgerc
      - run: echo access_token = $access_token >> .edgerc
      - run: echo client_token = $client_token >> .edgerc
      - run: ls -lhart
      - run: echo $EWVERSION
      - run: akamai ew status $EWID --versionId $EWVERSION --accountkey $ACCOUNTKEY