# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: akamai/edgeworkers
    environment:
      EWVERSION: 0.27
      EWID: 4885
      ACCOUNTKEY: 1-6JHGX
    working_directory: /root/edgeworkers
    steps:
      - checkout
      - run: echo "[default]" > .edgerc
      - run: echo client_secret = $client_secret >> .edgerc
      - run: echo host = $host >> .edgerc
      - run: echo access_token = $access_token >> .edgerc
      - run: echo client_token = $client_token >> .edgerc
      - run: tar -czvf ./control-cache.tgz bundle.json main.js
      - run: akamai ew upload --bundle ./control-cache.tgz $EWID --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
      - run: akamai ew activate $EWID STAGING $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
      - run: akamai ew status $EWID --versionId $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY

workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - edgerc
      - node/test