# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: akamai/edgeworkers
    environment:
      EWVERSION: 1.53
      EWID: 4885
      BUNDLENAME: ew-bundle.tgz
      DESCRIPTION: "EW Deployment Automation with CircleCI"
    working_directory: /root/edgeworkers
    steps:
      - checkout
      - run: 
          name: "Build .edgerc file"
          command: echo -e "[default]\nclient_secret = $CLIENT_SECRET\nhost = $HOST\naccess_token = $ACCESS_TOKEN\nclient_token = $CLIENT_TOKEN" > .edgerc
      - run:
          name: Create Artifact
          command: |
            sed -i 's|EWVERSION|'$EWVERSION'|g' bundle.json
            sed -i "s|DESCRIPTION|$DESCRIPTION|g" bundle.json
            tar -czvf ./$BUNDLENAME main.js bundle.json find-replace-stream.js
      - store_artifacts:
          path: ew-bundle.tgz
      - run: 
          name: Upload and Activate EW Bundle
          command: |
            akamai ew upload --bundle ./$BUNDLENAME $EWID --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
            akamai ew activate $EWID STAGING $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
            akamai ew status $EWID --versionId $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
      - run:
          name: "Activation in Progress"
          command: while :; do OUTPUT=`akamai ew status $EWID --versionId $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY | awk '/PRESUBMIT|PENDING|IN_PROGRESS/ { print $4 }'`; if [ -z $OUTPUT ]; then echo Activation COMPLETE; break; else sleep 5; fi; done
      - run:
          name: "Enable Enhanced Debugging Token"
          command: |
            akamai ew --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY auth --expiry 60 --acl /json-inline-demo --network staging $HOSTNAME || true 

workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - edgerc
          post-steps:
            - run: 
                name: "Remove .edgerc"
                command: rm -r .edgerc
