# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: akamai/edgeworkers
    environment:
      EWVERSION: 0.42
      EWID: 4885
      ACCOUNTKEY: 1-6JHGX
      BUNDLENAME: jaescalo-testing.tgz
      DESCRIPTION: "Testing deploy command"
    working_directory: /root/edgeworkers
    steps:
      - checkout
      - run: 
          name: "Build .edgerc file"
          command: echo -e "[default]\nclient_secret = $CLIENT_SECRET\nhost = $HOST\naccess_token = $ACCESS_TOKEN\nclient_token = $CLIENT_TOKEN" > .edgerc
      - run:
          name: Create Artifact
          command: |
            echo "{"edgeworker-version":\"$EWVERSION\","description":\"$DESCRIPTION\"}" > bundle.json
            tar -czvf ./$BUNDLENAME main.js bundle.json
      
      - store_artifacts:
          path: /root/edgeworkers/${BUNDLENAME}
          destination: ${BUNDLENAME}

      - run: 
          name: Upload Artifact
          command: |
            akamai ew upload --bundle ./$BUNDLENAME $EWID --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
            akamai ew activate $EWID STAGING $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
            akamai ew status $EWID --versionId $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY
      - run:
          name: "Activation in Progress"
          command: while :; do OUTPUT=`akamai ew status $EWID --versionId $EWVERSION --edgerc /root/edgeworkers/.edgerc --accountkey $ACCOUNTKEY | awk '/PRESUBMIT|PENDING|IN_PROGRESS/ { print $4 }'`; if [ -z $OUTPUT ]; then echo Activation COMPLETE; break; else sleep 5; fi; done
  test:
    executor: node/default
    steps:
      - store_test_results:
          path: test

workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - edgerc
          pre-steps:
            - run:
                name: "Install curl"
                command: apk --no-cache add curl
            - run:
                name: "Install jFrog CLI"
                command: |
                  cd /root
                  curl -fL https://getcli.jfrog.io | sh
                  ls -lhart
          post-steps:
            - run: 
                name: "Remove .edgerc"
                command: rm -r .edgerc
      #- node/test
      #- test