# This file demonstrates how to leverage dynamic configuration to execute a separate config file using scripts.

version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.0
jobs:
  generate-config:
    executor: continuation/default
    environment:
      EW_NEW_VERSION: 0.55
      DESCRIPTION: "Test for CircleCI Dynamic Configs"
      USE_EDGEKV: false
      ACTIVATE_PRODUCTION: false
    steps:
      - checkout
      - run: 
          name: Generate EW Deployment akamai-ew.yml file
          command: |
            #The generate script has 2 arguments: 1) Edgeworkers Version 2) Description 3) Push to production? (true|false) 4) Uses EdgeKV? (true|false)
            ./update-ew-config-files.sh $EW_NEW_VERSION $DESCRIPTION `$USE_EDGEKV` `$ACTIVATE_PRODUCTION`
            cat bundle.json
            cat ./configs/akamai-ew.yml
      - continuation/continue:
          parameters: '{}'
          configuration_path: configs/akamai-ew.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config