# This file demonstrates how to leverage dynamic configuration to execute a separate config file using scripts.

version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.0
jobs:
  generate-config:
    executor: continuation/default
    
    # Modify the following variables as needed for each deployment 1) Edgeworkers Version 2) Description 3) Push to production? (true|false) 4) Uses EdgeKV? (true|false)
    environment:
      EW_NEW_VERSION: 0.57
      DESCRIPTION: "Test for CircleCI Dynamic Configs"
      USE_EDGEKV: false
      ACTIVATE_PRODUCTION: false

    steps:
      - checkout
      - run: 
          name: Generate EW Deployment akamai-ew.yml file
          command: |
            # The update-ew-config-files.sh script takes the environment variables from above as parameters
            ./update-ew-config-files.sh $EW_NEW_VERSION '$DESCRIPTION' $USE_EDGEKV $ACTIVATE_PRODUCTION
            cat bundle.json
            cat ./configs/akamai-ew.yml
      - continuation/continue:
          parameters: '{}'
          configuration_path: configs/akamai-ew.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config