# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - edgerc

jobs:
  build:
    docker:
      - image: akamai/edgeworkers

    steps:
      - run: echo "[default]" > .edgerc
      - run: echo client_secret = $client_secret >> .edgerc
      - run: echo host = $host >> .edgerc
      - run: echo access_token = $access_token >> .edgerc
      - run: echo client_token = $client_token >> .edgerc
      - run: EWVERSION=0.11
      - run: echo $EWVERSION
      - run: akamai ew status 4885 --versionId $EWVERSION --accountkey 1-6JHGX